spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/micro-admin?zoneDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&AutoReconnect=ture
    username: ${mysql.username}
    password: ${mysql.password}

  redis:
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}

  cache:
    # 缓存类型
    type: redis
    redis:
      # 缓存时间(单位 ms)
      time-to-live: 3600000
      # 缓存 null 值，防止缓存穿透
      cache-null-values: true
      # 是否启用前缀
      use-key-prefix: true
      # 前缀名
      key-prefix: "admin:"

mybatis-plus:
  configuration:
    # 下划线自动转换大写
    map-underscore-to-camel-case: true
    # 这个配置会将执行的 sql 打印出来，在开发和测试的时候可以打开使用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/*.xml

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

feign:
  httpClient:
    enabled: true
  okhttp:
    enabled: false

